In [1]:
from dash import Dash, html, dcc, Output, Input, dash_table, callback   # pip install dash
import dash_bootstrap_components as dbc                                  # pip install dash-bootstrap-components
import plotly.express as px
import pandas as pd
import numpy as np

app = Dash(__name__, external_stylesheets=[dbc.themes.LUMEN, dbc.icons.FONT_AWESOME])
server = app.server

In [46]:
df = pd.read_csv('https://raw.githubusercontent.com/Coding-with-Adam/Dash-by-Plotly/master/Analytic_Web_Apps/Flights_Analysis/europe-flights-reduced.csv')
df['YEAR'] = df['YEAR'].astype(str)

In [47]:
df

,TIME,YEAR,GEO,UNIT,TRA_MEAS,PARTNER,Value,Flag and Footnotes,MONTH
0,2021M02,2021,Belgique,Passager,Passagers à bord (arrivées),Belgique,186,NaN,2
1,2021M02,2021,Belgique,Passager,Passagers à bord (arrivées),Bulgarie,956,NaN,2
2,2021M02,2021,Belgique,Passager,Passagers à bord (arrivées),Tchéquie,31,NaN,2
3,2021M02,2021,Belgique,Passager,Passagers à bord (arrivées),Danemark,750,NaN,2
4,2021M02,2021,Belgique,Passager,Passagers à bord (arrivées),Allemagne,4169,NaN,2
...,...,...,...,...,...,...,...,...,...
187487,2019M07,2019,Turquie,Passager,Passagers à bord,Royaume-Uni,918813,NaN,7
187488,2019M07,2019,Turquie,Passager,Passagers à bord,Monténégro,12929,NaN,7
187489,2019M07,2019,Turquie,Passager,Passagers à bord,Macédoine du Nord,41765,NaN,7
187490,2019M07,2019,Turquie,Passager,Passagers à bord,Serbie,68915,NaN,7
187491,2019M07,2019,Turquie,Passager,Passagers à bord,Turquie,4602247,NaN,7

In [48]:
pbc = df.groupby(['GEO','PARTNER'])['Value'].sum()

In [49]:
pbc

GEO        PARTNER
Allemagne  Allemagne    135929712
           Autriche      43897164
           Belgique      11157960
           Bulgarie      15628444
           Chypre         3213418
                          ...
Turquie    Slovénie        431588
           Suisse         3749702
           Suède          2610328
           Tchéquie       1974140
           Turquie      150403318
Name: Value, Length: 1211, dtype: int64

In [50]:
pbc = df.groupby(['GEO','PARTNER'])['Value'].sum().reset_index()

In [51]:
pbc

            GEO    PARTNER      Value
0     Allemagne  Allemagne  135929712
1     Allemagne   Autriche   43897164
2     Allemagne   Belgique   11157960
3     Allemagne   Bulgarie   15628444
4     Allemagne     Chypre    3213418
...         ...        ...        ...
1206    Turquie   Slovénie     431588
1207    Turquie     Suisse    3749702
1208    Turquie      Suède    2610328
1209    Turquie   Tchéquie    1974140
1210    Turquie    Turquie  150403318

[1211 rows x 3 columns]

In [52]:
pbc = pbc.pivot(index='GEO', columns='PARTNER')['Value'].reset_index()

In [53]:
pbc

PARTNER,GEO,Allemagne,Autriche,Belgique,Bulgarie,Chypre,Croatie,Danemark,Espagne,Estonie,...,Portugal,Roumanie,Royaume-Uni,Serbie,Slovaquie,Slovénie,Suisse,Suède,Tchéquie,Turquie
0,Allemagne,135929712.0,43897164.0,11157960.0,15628444.0,3213418.0,16220238.0,18146184.0,190499844.0,2980194.0,...,35753662.0,20118358.0,78954420.0,7405380.0,74194.0,1560518.0,40701264.0,20249062.0,6459034.0,123400326.0
1,Autriche,43327562.0,3240416.0,3332958.0,3455000.0,2189946.0,2329138.0,3487044.0,16197670.0,371350.0,...,3093206.0,4493558.0,13239360.0,1791612.0,427068.0,184976.0,9514740.0,2778246.0,977200.0,9315250.0
2,Belgique,10632508.0,3232944.0,132290.0,2065312.0,415342.0,1608214.0,3895896.0,40943028.0,361964.0,...,11229592.0,4647200.0,8424308.0,228204.0,336110.0,586788.0,5546170.0,3380692.0,2583184.0,6928250.0
3,Bulgarie,14831392.0,3322076.0,1984222.0,2383726.0,1013852.0,24010.0,951866.0,3525536.0,247636.0,...,177736.0,307628.0,12576026.0,190158.0,826514.0,34990.0,610122.0,203154.0,2681490.0,2454994.0
4,Chypre,3241984.0,2229012.0,431986.0,1065986.0,3290.0,11214.0,819828.0,22248.0,317272.0,...,1368.0,1615978.0,18544188.0,483192.0,491998.0,592.0,991294.0,1346942.0,305304.0,NaN
5,Croatie,15567008.0,2284924.0,1593976.0,30716.0,1604.0,3753416.0,1534670.0,2005924.0,30700.0,...,189090.0,80096.0,9959948.0,622720.0,22688.0,13676.0,1932190.0,2098876.0,820280.0,1610766.0
6,Danemark,16437920.0,3325472.0,3771154.0,942566.0,727638.0,1475604.0,13688850.0,18613724.0,618532.0,...,2295844.0,1436520.0,18232964.0,341484.0,900.0,104966.0,4363486.0,9739274.0,1864350.0,6503066.0
7,Espagne,188684080.0,16220072.0,43283308.0,3665020.0,24706.0,2012884.0,20627104.0,331261832.0,436012.0,...,34768702.0,12848580.0,247359860.0,353286.0,620124.0,47072.0,33622816.0,23123742.0,7813498.0,2404988.0
8,Estonie,2745944.0,332620.0,351612.0,252092.0,280356.0,30528.0,614484.0,380800.0,334692.0,...,18936.0,9868.0,1284520.0,736.0,244.0,2512.0,48512.0,1579812.0,380.0,1242164.0
9,Finlande,12755786.0,1299458.0,1433822.0,290202.0,220966.0,968528.0,4929652.0,10104752.0,2124296.0,...,1366268.0,276174.0,8626942.0,58646.0,11596.0,138114.0,2100360.0,10641400.0,1539370.0,2444828.0
10,France,48438024.0,8643778.0,14557264.0,2347498.0,191078.0,4779466.0,8777238.0,91422220.0,294016.0,...,49485648.0,8060178.0,66114596.0,2808844.0,160230.0,613976.0,26394406.0,7109916.0,6409522.0,17612472.0
11,Grèce,49517728.0,7113164.0,6624060.0,1520564.0,9995032.0,412460.0,4984148.0,4491712.0,339112.0,...,609968.0,3367236.0,41359264.0,1497712.0,1102580.0,491528.0,7531068.0,5367248.0,4866596.0,5067280.0
12,Hongrie,12686836.0,517518.0,2972468.0,443866.0,964724.0,36996.0,1633268.0,6135142.0,428.0,...,1462876.0,842182.0,14391506.0,23166.0,5756.0,716.0,3600988.0,2098780.0,1219940.0,3175856.0
13,Irlande,12640368.0,1375454.0,2636942.0,684946.0,208952.0,1126116.0,1404514.0,23611172.0,124484.0,...,7042654.0,1798052.0,68082720.0,240.0,699144.0,736.0,2299322.0,919946.0,1075120.0,1607902.0
14,Islande,3923836.0,448132.0,562700.0,634.0,NaN,9462.0,3921192.0,2031372.0,220.0,...,24918.0,1612.0,7403480.0,NaN,3666.0,8200.0,872072.0,1122428.0,139334.0,4136.0
15,Italie,84182292.0,11972552.0,21540894.0,4296592.0,700480.0,2090520.0,8209770.0,92419024.0,593696.0,...,14716244.0,22881388.0,83782796.0,1443704.0,1056434.0,9570.0,14577706.0,4226776.0,7972212.0,16483182.0
16,Lettonie,6222732.0,947212.0,886316.0,158840.0,431164.0,210334.0,1661418.0,1552884.0,1930732.0,...,199000.0,416.0,5295296.0,3324.0,20380.0,2668.0,748812.0,1779904.0,635648.0,1343932.0
17,Lituanie,3786658.0,456964.0,611684.0,245764.0,465630.0,23624.0,2359430.0,1658064.0,486422.0,...,140748.0,460.0,7605524.0,3912.0,224.0,2460.0,3418.0,1023680.0,1394.0,2915010.0
18,Luxembourg,3522740.0,811168.0,7320.0,188648.0,2924.0,79184.0,417784.0,4697510.0,176.0,...,6404118.0,39900.0,3080142.0,15512.0,1068.0,240.0,959900.0,87924.0,56316.0,845944.0
19,Macédoine du Nord,4194100.0,985056.0,366108.0,680.0,75064.0,416688.0,296444.0,184852.0,324.0,...,556.0,5620.0,462988.0,299700.0,396276.0,165868.0,1172464.0,1507160.0,NaN,2502460.0
20,Malte,5728216.0,1034338.0,1488688.0,379550.0,155084.0,24214.0,519676.0,2348744.0,96028.0,...,555290.0,401612.0,10140926.0,360362.0,217536.0,28292.0,958626.0,462080.0,206424.0,1183664.0
21,Monténégro,1030692.0,484440.0,259544.0,5876.0,4088.0,3872.0,67284.0,95916.0,22148.0,...,476.0,612.0,570068.0,3358196.0,12792.0,258240.0,184584.0,194216.0,65976.0,941568.0
22,Norvège,10888438.0,1409574.0,1632508.0,386048.0,505430.0,1523464.0,16570348.0,16113216.0,780344.0,...,1082724.0,515388.0,14098792.0,407616.0,3880.0,7568.0,1386720.0,9874302.0,805404.0,3320136.0
23,Pays-Bas,29019464.0,9089750.0,2188100.0,3261586.0,709570.0,4064868.0,12097724.0,63085532.0,602356.0,...,17618372.0,5224216.0,63165238.0,1736600.0,147212.0,470448.0,13803830.0,9876546.0,5619466.0,18432126.0
24,Pologne,26968962.0,3010986.0,4885864.0,5065278.0,2158384.0,2098608.0,5016524.0,15550304.0,1093366.0,...,3411190.0,1470488.0,49427762.0,399172.0,214938.0,275814.0,3656028.0,8675774.0,1534426.0,11640290.0
25,Portugal,35181488.0,3098736.0,11600640.0,190990.0,1744.0,189938.0,2544906.0,35200998.0,20558.0,...,39273860.0,622410.0,53874506.0,2744.0,2466.0,9196.0,18953394.0,1957842.0,1080624.0,1921972.0
26,Roumanie,18653714.0,4241924.0,4511768.0,279908.0,1518988.0,75320.0,1433768.0,12210788.0,NaN,...,573768.0,9132092.0,22264372.0,345394.0,1124.0,36.0,1647170.0,1368148.0,572814.0,7120738.0
27,Royaume-Uni,71219752.0,12295276.0,7600264.0,10918010.0,14765212.0,8239592.0,17392586.0,209417770.0,1156488.0,...,43636532.0,18602758.0,115758278.0,900488.0,3695970.0,1054768.0,30964170.0,13081896.0,11629200.0,34406950.0
28,Serbie,5981316.0,1436856.0,196068.0,181672.0,348296.0,541672.0,308628.0,288672.0,724.0,...,820.0,1752.0,980708.0,776.0,148472.0,445764.0,3190022.0,1736672.0,189760.0,3157198.0
29,Slovaquie,76642.0,432192.0,347596.0,761208.0,488332.0,47406.0,20278.0,620124.0,360.0,...,1872.0,2466.0,4071286.0,147458.0,15622.0,1708.0,6226.0,42544.0,391054.0,1224100.0
30,Slovénie,1536628.0,181676.0,605304.0,34420.0,19656.0,11400.0,104452.0,47996.0,1740.0,...,7624.0,NaN,1117036.0,506940.0,1680.0,NaN,444256.0,596.0,42928.0,1028432.0
31,Suisse,38037970.0,8902172.0,5822808.0,872360.0,1043132.0,2497162.0,4907076.0,39083202.0,47868.0,...,19196706.0,1971276.0,36766364.0,3694388.0,2972.0,431050.0,3961972.0,3890716.0,2193504.0,14215158.0
32,Suède,18541614.0,2630200.0,3285062.0,203598.0,1212242.0,2073962.0,9708346.0,20655668.0,1585470.0,...,1777224.0,1368944.0,13497382.0,2000186.0,35236.0,3272.0,3814650.0,41221682.0,1575842.0,6679698.0
33,Tchéquie,6538664.0,1002408.0,2669742.0,2717360.0,330910.0,845022.0,2007880.0,7814862.0,3372.0,...,1077148.0,609780.0,12611742.0,276584.0,403430.0,49474.0,2053612.0,1625766.0,229362.0,4887370.0
34,Turquie,42427476.0,3341638.0,3396022.0,949696.0,NaN,598304.0,2688682.0,3628974.0,443704.0,...,727658.0,2745130.0,17350606.0,1353558.0,650064.0,431588.0,3749702.0,2610328.0,1974140.0,150403318.0

In [54]:
    pbc = pbc[pbc['GEO'].isin(['Allemagne','Espagne','France','Grèce','Italie',
                               'Pays-Bas','Portugal','Royaume-Uni','Suisse','Turquie'])]

In [55]:
pbc

PARTNER,GEO,Allemagne,Autriche,Belgique,Bulgarie,Chypre,Croatie,Danemark,Espagne,Estonie,...,Portugal,Roumanie,Royaume-Uni,Serbie,Slovaquie,Slovénie,Suisse,Suède,Tchéquie,Turquie
0,Allemagne,135929712.0,43897164.0,11157960.0,15628444.0,3213418.0,16220238.0,18146184.0,190499844.0,2980194.0,...,35753662.0,20118358.0,78954420.0,7405380.0,74194.0,1560518.0,40701264.0,20249062.0,6459034.0,123400326.0
7,Espagne,188684080.0,16220072.0,43283308.0,3665020.0,24706.0,2012884.0,20627104.0,331261832.0,436012.0,...,34768702.0,12848580.0,247359860.0,353286.0,620124.0,47072.0,33622816.0,23123742.0,7813498.0,2404988.0
10,France,48438024.0,8643778.0,14557264.0,2347498.0,191078.0,4779466.0,8777238.0,91422220.0,294016.0,...,49485648.0,8060178.0,66114596.0,2808844.0,160230.0,613976.0,26394406.0,7109916.0,6409522.0,17612472.0
11,Grèce,49517728.0,7113164.0,6624060.0,1520564.0,9995032.0,412460.0,4984148.0,4491712.0,339112.0,...,609968.0,3367236.0,41359264.0,1497712.0,1102580.0,491528.0,7531068.0,5367248.0,4866596.0,5067280.0
15,Italie,84182292.0,11972552.0,21540894.0,4296592.0,700480.0,2090520.0,8209770.0,92419024.0,593696.0,...,14716244.0,22881388.0,83782796.0,1443704.0,1056434.0,9570.0,14577706.0,4226776.0,7972212.0,16483182.0
23,Pays-Bas,29019464.0,9089750.0,2188100.0,3261586.0,709570.0,4064868.0,12097724.0,63085532.0,602356.0,...,17618372.0,5224216.0,63165238.0,1736600.0,147212.0,470448.0,13803830.0,9876546.0,5619466.0,18432126.0
25,Portugal,35181488.0,3098736.0,11600640.0,190990.0,1744.0,189938.0,2544906.0,35200998.0,20558.0,...,39273860.0,622410.0,53874506.0,2744.0,2466.0,9196.0,18953394.0,1957842.0,1080624.0,1921972.0
27,Royaume-Uni,71219752.0,12295276.0,7600264.0,10918010.0,14765212.0,8239592.0,17392586.0,209417770.0,1156488.0,...,43636532.0,18602758.0,115758278.0,900488.0,3695970.0,1054768.0,30964170.0,13081896.0,11629200.0,34406950.0
31,Suisse,38037970.0,8902172.0,5822808.0,872360.0,1043132.0,2497162.0,4907076.0,39083202.0,47868.0,...,19196706.0,1971276.0,36766364.0,3694388.0,2972.0,431050.0,3961972.0,3890716.0,2193504.0,14215158.0
34,Turquie,42427476.0,3341638.0,3396022.0,949696.0,NaN,598304.0,2688682.0,3628974.0,443704.0,...,727658.0,2745130.0,17350606.0,1353558.0,650064.0,431588.0,3749702.0,2610328.0,1974140.0,150403318.0

In [56]:
sums_col = pbc.select_dtypes(np.number).sum()

In [57]:
pbc = pd.concat([pbc, sums_col.to_frame().T], ignore_index=True)

In [58]:
pbc

PARTNER,GEO,Allemagne,Autriche,Belgique,Bulgarie,Chypre,Croatie,Danemark,Espagne,Estonie,...,Portugal,Roumanie,Royaume-Uni,Serbie,Slovaquie,Slovénie,Suisse,Suède,Tchéquie,Turquie
0,Allemagne,135929712.0,43897164.0,11157960.0,15628444.0,3213418.0,16220238.0,18146184.0,1.904998e+08,2980194.0,...,35753662.0,20118358.0,78954420.0,7405380.0,74194.0,1560518.0,40701264.0,20249062.0,6459034.0,123400326.0
1,Espagne,188684080.0,16220072.0,43283308.0,3665020.0,24706.0,2012884.0,20627104.0,3.312618e+08,436012.0,...,34768702.0,12848580.0,247359860.0,353286.0,620124.0,47072.0,33622816.0,23123742.0,7813498.0,2404988.0
2,France,48438024.0,8643778.0,14557264.0,2347498.0,191078.0,4779466.0,8777238.0,9.142222e+07,294016.0,...,49485648.0,8060178.0,66114596.0,2808844.0,160230.0,613976.0,26394406.0,7109916.0,6409522.0,17612472.0
3,Grèce,49517728.0,7113164.0,6624060.0,1520564.0,9995032.0,412460.0,4984148.0,4.491712e+06,339112.0,...,609968.0,3367236.0,41359264.0,1497712.0,1102580.0,491528.0,7531068.0,5367248.0,4866596.0,5067280.0
4,Italie,84182292.0,11972552.0,21540894.0,4296592.0,700480.0,2090520.0,8209770.0,9.241902e+07,593696.0,...,14716244.0,22881388.0,83782796.0,1443704.0,1056434.0,9570.0,14577706.0,4226776.0,7972212.0,16483182.0
5,Pays-Bas,29019464.0,9089750.0,2188100.0,3261586.0,709570.0,4064868.0,12097724.0,6.308553e+07,602356.0,...,17618372.0,5224216.0,63165238.0,1736600.0,147212.0,470448.0,13803830.0,9876546.0,5619466.0,18432126.0
6,Portugal,35181488.0,3098736.0,11600640.0,190990.0,1744.0,189938.0,2544906.0,3.520100e+07,20558.0,...,39273860.0,622410.0,53874506.0,2744.0,2466.0,9196.0,18953394.0,1957842.0,1080624.0,1921972.0
7,Royaume-Uni,71219752.0,12295276.0,7600264.0,10918010.0,14765212.0,8239592.0,17392586.0,2.094178e+08,1156488.0,...,43636532.0,18602758.0,115758278.0,900488.0,3695970.0,1054768.0,30964170.0,13081896.0,11629200.0,34406950.0
8,Suisse,38037970.0,8902172.0,5822808.0,872360.0,1043132.0,2497162.0,4907076.0,3.908320e+07,47868.0,...,19196706.0,1971276.0,36766364.0,3694388.0,2972.0,431050.0,3961972.0,3890716.0,2193504.0,14215158.0
9,Turquie,42427476.0,3341638.0,3396022.0,949696.0,NaN,598304.0,2688682.0,3.628974e+06,443704.0,...,727658.0,2745130.0,17350606.0,1353558.0,650064.0,431588.0,3749702.0,2610328.0,1974140.0,150403318.0
10,NaN,722637986.0,124574302.0,127771320.0,43650760.0,30644372.0,41105432.0,100375418.0,1.060511e+09,6914004.0,...,255787352.0,96441530.0,804485928.0,21196704.0,7512246.0,5119714.0,194260328.0,91494072.0,56017796.0,384347772.0

In [59]:
pbc.at[10, 'GEO'] = 'Total'

In [60]:
pbc

PARTNER,GEO,Allemagne,Autriche,Belgique,Bulgarie,Chypre,Croatie,Danemark,Espagne,Estonie,...,Portugal,Roumanie,Royaume-Uni,Serbie,Slovaquie,Slovénie,Suisse,Suède,Tchéquie,Turquie
0,Allemagne,135929712.0,43897164.0,11157960.0,15628444.0,3213418.0,16220238.0,18146184.0,1.904998e+08,2980194.0,...,35753662.0,20118358.0,78954420.0,7405380.0,74194.0,1560518.0,40701264.0,20249062.0,6459034.0,123400326.0
1,Espagne,188684080.0,16220072.0,43283308.0,3665020.0,24706.0,2012884.0,20627104.0,3.312618e+08,436012.0,...,34768702.0,12848580.0,247359860.0,353286.0,620124.0,47072.0,33622816.0,23123742.0,7813498.0,2404988.0
2,France,48438024.0,8643778.0,14557264.0,2347498.0,191078.0,4779466.0,8777238.0,9.142222e+07,294016.0,...,49485648.0,8060178.0,66114596.0,2808844.0,160230.0,613976.0,26394406.0,7109916.0,6409522.0,17612472.0
3,Grèce,49517728.0,7113164.0,6624060.0,1520564.0,9995032.0,412460.0,4984148.0,4.491712e+06,339112.0,...,609968.0,3367236.0,41359264.0,1497712.0,1102580.0,491528.0,7531068.0,5367248.0,4866596.0,5067280.0
4,Italie,84182292.0,11972552.0,21540894.0,4296592.0,700480.0,2090520.0,8209770.0,9.241902e+07,593696.0,...,14716244.0,22881388.0,83782796.0,1443704.0,1056434.0,9570.0,14577706.0,4226776.0,7972212.0,16483182.0
5,Pays-Bas,29019464.0,9089750.0,2188100.0,3261586.0,709570.0,4064868.0,12097724.0,6.308553e+07,602356.0,...,17618372.0,5224216.0,63165238.0,1736600.0,147212.0,470448.0,13803830.0,9876546.0,5619466.0,18432126.0
6,Portugal,35181488.0,3098736.0,11600640.0,190990.0,1744.0,189938.0,2544906.0,3.520100e+07,20558.0,...,39273860.0,622410.0,53874506.0,2744.0,2466.0,9196.0,18953394.0,1957842.0,1080624.0,1921972.0
7,Royaume-Uni,71219752.0,12295276.0,7600264.0,10918010.0,14765212.0,8239592.0,17392586.0,2.094178e+08,1156488.0,...,43636532.0,18602758.0,115758278.0,900488.0,3695970.0,1054768.0,30964170.0,13081896.0,11629200.0,34406950.0
8,Suisse,38037970.0,8902172.0,5822808.0,872360.0,1043132.0,2497162.0,4907076.0,3.908320e+07,47868.0,...,19196706.0,1971276.0,36766364.0,3694388.0,2972.0,431050.0,3961972.0,3890716.0,2193504.0,14215158.0
9,Turquie,42427476.0,3341638.0,3396022.0,949696.0,NaN,598304.0,2688682.0,3.628974e+06,443704.0,...,727658.0,2745130.0,17350606.0,1353558.0,650064.0,431588.0,3749702.0,2610328.0,1974140.0,150403318.0
10,Total,722637986.0,124574302.0,127771320.0,43650760.0,30644372.0,41105432.0,100375418.0,1.060511e+09,6914004.0,...,255787352.0,96441530.0,804485928.0,21196704.0,7512246.0,5119714.0,194260328.0,91494072.0,56017796.0,384347772.0

In [62]:
sums_r = pbc.select_dtypes(np.number).sum(axis=1)
pbc['total'] = sums_r

In [63]:
pbc

PARTNER,GEO,Allemagne,Autriche,Belgique,Bulgarie,Chypre,Croatie,Danemark,Espagne,Estonie,...,Roumanie,Royaume-Uni,Serbie,Slovaquie,Slovénie,Suisse,Suède,Tchéquie,Turquie,total
0,Allemagne,135929712.0,43897164.0,11157960.0,15628444.0,3213418.0,16220238.0,18146184.0,1.904998e+08,2980194.0,...,20118358.0,78954420.0,7405380.0,74194.0,1560518.0,40701264.0,20249062.0,6459034.0,123400326.0,1.122495e+09
1,Espagne,188684080.0,16220072.0,43283308.0,3665020.0,24706.0,2012884.0,20627104.0,3.312618e+08,436012.0,...,12848580.0,247359860.0,353286.0,620124.0,47072.0,33622816.0,23123742.0,7813498.0,2404988.0,1.327884e+09
2,France,48438024.0,8643778.0,14557264.0,2347498.0,191078.0,4779466.0,8777238.0,9.142222e+07,294016.0,...,8060178.0,66114596.0,2808844.0,160230.0,613976.0,26394406.0,7109916.0,6409522.0,17612472.0,7.717690e+08
3,Grèce,49517728.0,7113164.0,6624060.0,1520564.0,9995032.0,412460.0,4984148.0,4.491712e+06,339112.0,...,3367236.0,41359264.0,1497712.0,1102580.0,491528.0,7531068.0,5367248.0,4866596.0,5067280.0,2.829207e+08
4,Italie,84182292.0,11972552.0,21540894.0,4296592.0,700480.0,2090520.0,8209770.0,9.241902e+07,593696.0,...,22881388.0,83782796.0,1443704.0,1056434.0,9570.0,14577706.0,4226776.0,7972212.0,16483182.0,8.121681e+08
5,Pays-Bas,29019464.0,9089750.0,2188100.0,3261586.0,709570.0,4064868.0,12097724.0,6.308553e+07,602356.0,...,5224216.0,63165238.0,1736600.0,147212.0,470448.0,13803830.0,9876546.0,5619466.0,18432126.0,3.900308e+08
6,Portugal,35181488.0,3098736.0,11600640.0,190990.0,1744.0,189938.0,2544906.0,3.520100e+07,20558.0,...,622410.0,53874506.0,2744.0,2466.0,9196.0,18953394.0,1957842.0,1080624.0,1921972.0,3.172682e+08
7,Royaume-Uni,71219752.0,12295276.0,7600264.0,10918010.0,14765212.0,8239592.0,17392586.0,2.094178e+08,1156488.0,...,18602758.0,115758278.0,900488.0,3695970.0,1054768.0,30964170.0,13081896.0,11629200.0,34406950.0,1.041169e+09
8,Suisse,38037970.0,8902172.0,5822808.0,872360.0,1043132.0,2497162.0,4907076.0,3.908320e+07,47868.0,...,1971276.0,36766364.0,3694388.0,2972.0,431050.0,3961972.0,3890716.0,2193504.0,14215158.0,2.732461e+08
9,Turquie,42427476.0,3341638.0,3396022.0,949696.0,NaN,598304.0,2688682.0,3.628974e+06,443704.0,...,2745130.0,17350606.0,1353558.0,650064.0,431588.0,3749702.0,2610328.0,1974140.0,150403318.0,2.734690e+08
10,Total,722637986.0,124574302.0,127771320.0,43650760.0,30644372.0,41105432.0,100375418.0,1.060511e+09,6914004.0,...,96441530.0,804485928.0,21196704.0,7512246.0,5119714.0,194260328.0,91494072.0,56017796.0,384347772.0,6.612420e+09